cucumber/cucumber-ruby-core

lib/cucumber/core/test/case.rb
spec/cucumber/core/test/case_spec.rb
spec/cucumber/core_spec.rb

This PR starts working on [cucumber issue #768](https://github.com/cucumber/cucumber/issues/768) where we want a name like "scenario name" not "Scenario: scenario name"
@mattwynne and @akostadinov, let me know if this is the direction you were thinking.  There were two other requests in the issue about wanting values from an example table and a separate method to get row numbers, but I'm not entirely sure what the end goal is.
How would these details be used? ... Can you give me an example? :smile: 
I'm not completely sure just sticking on extra results to the `NameBuilder` is the way to go either, but this does give the simplified name now.

names in Test::Case

---

lib/cucumber/core/test/result.rb
lib/cucumber/core/test/runner.rb
spec/cucumber/core/test/result_spec.rb
spec/cucumber/core/test/runner_spec.rb

To make the result objects usable in the new formatter api:
* Set the message on undefined results.
* Append the backtrace with the backtrace line of the step on results that either have an exception (with backtrace) or have a backtrace themselves.
* Support applying filters on the backtrace.
Required by cucumber/cucumber#843.

Make the result objects usable in the new formatter api

---

lib/cucumber/core/test/result.rb
spec/cucumber/core/test/result_spec.rb

Added for https://github.com/cucumber/cucumber/issues/836

Add #status to Cucumber::Core::Test::Result classes

---

lib/cucumber/core/test/result.rb
spec/cucumber/core/test/result_spec.rb

This could simplify logic where Pending and Undefined results in strict mode shall be handled in the same way as Failed results.
The first to use it is the JUnit Formatter (cucumber/cucumber#855)

Add Result#non_zero_exit_status?

---

Gemfile
cucumber-core.gemspec
lib/cucumber/core/ast/background.rb
lib/cucumber/core/ast/data_table.rb
lib/cucumber/core/ast/describes_itself.rb
lib/cucumber/core/ast/doc_string.rb
lib/cucumber/core/ast/examples_table.rb
lib/cucumber/core/ast/feature.rb
lib/cucumber/core/ast/location.rb
lib/cucumber/core/ast/outline_step.rb
lib/cucumber/core/ast/scenario.rb
lib/cucumber/core/ast/scenario_outline.rb
lib/cucumber/core/ast/step.rb
lib/cucumber/core/gherkin/ast_builder.rb
lib/cucumber/core/gherkin/parser.rb
lib/cucumber/core/gherkin/tag_expression.rb
lib/cucumber/core/test/case.rb
spec/cucumber/core/ast/background_spec.rb
spec/cucumber/core/ast/outline_step_spec.rb
spec/cucumber/core/ast/step_spec.rb
spec/cucumber/core/gherkin/parser_spec.rb
spec/cucumber/core/test/case_spec.rb

This PR make Cucumber-Ruby-Core use (the parser of) Gherkin3 instead of Gherkin2. Some notes:
* The one file apart from the parser that was used from Gherkin2 (tag_expression.rb), is copied into [Cucumber::Core:Gherkin](https://github.com/cucumber/cucumber-ruby-core/blob/d2dc089668c1ce9848791c8bc72807f9b77e8d4c/lib/cucumber/core/gherkin/tag_expression.rb) to remove all dependencies to Gherkin2.
* To be able to use the Gherkin3 parser, a hook method is needed in the parser to be able to subclass the Gherkin3::AstBuilder ([the integrate-ruby-core branch](https://github.com/cucumber/gherkin3/commit/bbb09f0c55067ae372f41a8e3aa6ad5bce86f95d))
* The Cucumber-Ruby-Core AST classes are not created directly from the parser, instead builder are still created by Cucumber::Core::Gherkin:AstBuilder …

Use Gherkin3 instead  of Gherkin2

---

spec/cucumber/core/test/filters/locations_filter_spec.rb

When the locations_filter was created to preserve the filter ordering from the command line when executing the test case (in Cucumber-Ruby-Core v1.1.0/Cucumber-Ruby v2.0.0.rc.4), so that `cucumber path/a_feature.feature:10:5` would result in that the test case of line 10 is executed before the test case of line 5, it had the side effect of allowing each test case to executed more than once when using line filter.
Previously `cucumber path/a_feature.feature:10:10:10` would result in that the test case of line 10 was executed once (as in Cucumber v1.3.x), now it results in the test case of line 10 is executed three times.
I think this is not what we want.
This PR contains a failing test for this problem, it is preferably fixed together with #96.

Run each test case at most once when using line filters

---

.rspec
Rakefile
lib/cucumber/core/ast/empty_multiline_argument.rb
lib/cucumber/core/ast/location.rb
lib/cucumber/core/ast/step.rb
lib/cucumber/core/test/case.rb
lib/cucumber/core/test/filters/locations_filter.rb
lib/cucumber/core/test/step.rb
spec/cucumber/core/ast/location_spec.rb
spec/cucumber/core/ast/step_spec.rb
spec/cucumber/core/test/filters/locations_filter_spec.rb

I think this is an improvement on the solution in #96, in that it's faster and seems to fit the existing model better.
@akostadinov could you give this a try please?

Refactor locations

---

lib/cucumber/core/test/timer.rb
spec/cucumber/core/test/timer_spec.rb

for reasons described in https://github.com/ruby-concurrency/concurrent-ruby/issues/256
closes #101

use monotonic time

---

lib/cucumber/core/test/result.rb
spec/cucumber/core/test/result_spec.rb

This pull request adds a `#with_filtered_backtrace` method to `Result::Unknown`, enabling Cucumber to handle empty scenarios more gracefully. Addresses this issue in Cucumber-Ruby: https://github.com/cucumber/cucumber-ruby/issues/967

Add with_filtered_backtrace method to unknown result

---

lib/cucumber/core/gherkin/document.rb
lib/cucumber/core/gherkin/parser.rb

This is a companion to [this PR](https://github.com/cucumber/cucumber-ruby/pull/989) against cucumber-ruby, which allows language to be passed in as a command line option. It allows the language to be passed into the `Cucumber::Core::Gherkin::Document` object on initialization, and creates a `TokenMatcher` object using that language when parsing the document.

Allow language to be passed into document object

---

.travis.yml
spec/cucumber/core/test/filters/locations_filter_spec.rb

In practice the only thing to do is to remove ruby v1.9.3 from the Travis matrix.

Remove support for Ruby v1.9.3

---

lib/cucumber/core/test/case.rb
spec/cucumber/core/test/case_spec.rb
spec/cucumber/core/test/runner_spec.rb

This will help finish off the retry feature on the UI

Implement equality for test cases

---

.travis.yml

Only Ruby 2.4.0 is failed on current master branch.
https://travis-ci.org/cucumber/cucumber-ruby-core/jobs/207769607
```
346 examples, 0 failures
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
```
The reason might look "spec:warnings" does not display errors when it includes warnings on Travis.
So, add Ruby 2.4.0 as allow_failures for coverage reports warnings.
I want to fix issue.
Travis tests it.

Add Ruby 2.4.0 as allow_failures for coverage reports warnings

---

.travis.yml

Remove Ruby 2.4 from allow_failures in .travis.yml.
Because coveralls 0.8.20 for Ruby 2.4 compatibility was released.
See also https://github.com/lemurheavy/coveralls-ruby/pull/117
Want to check on Ruby 2.4.
Travis will test it.

Remove Ruby 2.4 from allow_failures in .travis.yml.

---

HISTORY.md

The changelog `HISTORY.md` had a badly-rendered heading, and this PR repairs the Markdown rendering.
I removed a hard space character, and this made the `###` heading function again.

HISTORY.md: Remove a hard space

---

.travis.yml

This PR enables **test coverage data** in **JRuby** using the environment variable `JRUBY_OPTS=--debug`.
Travis output snippet **before**:
```
Finished in 8.04 seconds (files took 3.62 seconds to load)
346 examples, 0 failures
Coverage report generated for RSpec to
/home/travis/build/cucumber/cucumber-ruby-core/coverage.
0 / 4077 LOC (0.0%) covered.
```
Travis output snippet **after**:
```
Finished in 8.37 seconds (files took 5.94 seconds to load)
346 examples, 0 failures
Coverage report generated for RSpec to
/home/travis/build/cucumber/cucumber-ruby-core/coverage.
4048 / 4184 LOC (96.75%) covered.
```
(_Bonus_: We also pass `travis-lint` by adding the `language` key in the YAML configuration.)

Travis: Make JRuby produce test coverage info

---

lib/cucumber/core/ast/examples_table.rb
spec/cucumber/core/ast/examples_table_spec.rb

Added a method to allow the retrieval of a value in an AST Row by using the example table parameter that corresponds to it.
`Cucumber::Core::Ast::ExamplesTable::Row` now has a `#[]` method.
I wanted to be able to retrieve a value from a row without having to know ahead of time which position it would be in in the array returned by `#values`. I also didn't want to have to go through the effort of determining the index on the fly by accessing the header object, finding the index of the parameter name and then using that as the index for the value array. I just wanted a way to say "Hey, row! Give me the value that you used for this parameter!"
There's a spec for it.
There were a few failings specs but they were already failing and, given the very narrow nature of my change, are certainly not …

More versatile row value access.

---

lib/cucumber/core/event_bus.rb
spec/cucumber/core/event_bus_spec.rb

Replay previous events to new subscribers

---

lib/cucumber/core/test/result.rb
spec/cucumber/core/ast/doc_string_spec.rb
spec/cucumber/core/ast/location_spec.rb

This PR fixes tiny misspellings.
- Found using: `find . | misspellings -f -`

Fix misspellings

---

lib/cucumber/core/report/summary.rb
lib/cucumber/core/test/result.rb
spec/cucumber/core/report/summary_spec.rb
spec/cucumber/core/test/result_spec.rb

Make the Summary report able to say if the total result is ok.
* Add TYPES constant to Result module
* Make ok? class methods on the Result classes
* Make the Summary result able to way if the total result is ok.
The intention is to remove duplication and simplify the exit code logic in Cucumber-Ruby.
The logic of whether a certain result is ok or not is implemented in each `Result` class - and is used in several formatters. This logic should be used in more places, for instance in the exit code logic in Cucumber-Ruby.
The automated test suite has been updated to verify this behaviour.

Make the Summary report able to say if the total result is ok.

---

lib/cucumber/core/report/summary.rb
lib/cucumber/core/test/result.rb
spec/cucumber/core/report/summary_spec.rb
spec/cucumber/core/test/result_spec.rb

Add a flaky result type to be used for flaky scenarios.
Add a flaky result type to be used for flaky scenarios.
* The flaky result type should be ok in non-strict mode and not ok in
strict mode, so the exit code becomes zero with flaky scenarios in
non-strict mode.
* Update the Summary report to detect and count flaky scenarios.
Fixes https://github.com/cucumber/cucumber-ruby/issues/1044.
After the `--retry` feature was introduced it makes sense not to report each execution of the scenarios which are retried in the summary, but each retried scenario once - either as `failed` or `flaky` depending on if they passes after retry or not.
The automated test suite is updated to verify this new behaviour.

Add a flaky result type to be used for flaky scenarios.

---

lib/cucumber/core/report/summary.rb
lib/cucumber/core/test/result.rb
spec/cucumber/core/report/summary_spec.rb
spec/cucumber/core/test/result_spec.rb

Let the result types affected the the strict settings be controlled individually, so only a subset of the can be set to be handled strict.
Make it possible for each of the strict affected result types (`undefined`, `pending`, and `flaky`) to be controlled individually.
Needed by cucumber/cucumber-ruby#1169.
The automated test suite has been updated to verify this behaviour.

Handle selective strict settings.

---

lib/cucumber/core/compiler.rb
spec/cucumber/core/compiler_spec.rb
spec/cucumber/core/test/case_spec.rb
spec/cucumber/core/test/filters/locations_filter_spec.rb

Do not create test cases for scenarios with no steps.
To be consistent with the (Pickle) compiler in the Gherkin library, test cases should not be created for scenarios with no steps.
Fixing the root cause of cucumber/cucumber#243.
The automated test suite has been updated to verify this behaviour.
I have manually verified that `cucumber --dry-run` with empty scenarios does not raise the exception of  cucumber/cucumber#243 with this change.

Do not create test cases for scenarios with no steps.

---

lib/cucumber/core/gherkin/ast_builder.rb
spec/cucumber/core/test/filters/locations_filter_spec.rb

Hi folks! I'm back with another DataTable-related bugfix. When being built, DataTables would build their `Ast::Location` with only the first line. In the following example feature, this led to commands like `cucumber features/test.feature:5` working, but `cucumber features/test.feature:6` not running any tests, because no `Test::Case` reported containing that line.
```cucumber
Scenario: Run scenario with a data table
Given a file named "features/test.feature" with:
"""
Feature: 
Scenario: DataTable
Given this step is a table step
| a | b |
| c | d |
"""
When I run `cucumber features/test.feature:6 --format pretty --quiet`
Then it should pass with exactly:
"""
Feature: 
Scenario: DataTable
Given this step is a table step
| a | b |
| c | d |
1 scenario (1 passed)
1 step (1 passed)
"""
``` …

Fix DataTable's Location to be aware of all of its lines

---

CHANGELOG.md

CHANGELOG.md updates as per [cucumber/cucumber #251](https://github.com/cucumber/cucumber/issues/251)
* Renamed History.md to CHANGELOG.md
* Changed category names
* Added contributing message at top

CHANGELOG.md updates for monorepo's #251

---

.travis.yml

This PR updates JRuby to latest released - `jruby-9.1.13.0`.
The ENV var changes come from the Travis config og the [cucumber-ruby](https://github.com/cucumber/cucumber-ruby/blob/master/.travis.yml) project.

Travis: use jruby-9.1.13.0; add env LANG env vars

---

README.md
lib/cucumber/core/ast/outline_step.rb
lib/cucumber/core/ast/step.rb
lib/cucumber/core/test/filters/activate_steps_for_self_test.rb
lib/cucumber/core/test/runner.rb
lib/cucumber/core/test/step.rb
spec/cucumber/core/ast/outline_step_spec.rb
spec/cucumber/core/ast/step_spec.rb
spec/cucumber/core/compiler_spec.rb
spec/cucumber/core/filter_spec.rb
spec/cucumber/core/gherkin/parser_spec.rb
spec/cucumber/core/test/runner_spec.rb
spec/cucumber/core/test/step_spec.rb
spec/cucumber/core_spec.rb

This PR renames Step#name to Step#text and makes the RSpec tests pass.
Fixes #86

Step#name renamed to #text

---

.travis.yml

This PR updates the CI matrix to use latest JRuby.
http://jruby.org/2017/12/07/jruby-9-1-15-0.html

Travis: use jruby-9.1.15.0

---

lib/cucumber/core/ast/step.rb
lib/cucumber/core/test/step.rb
spec/cucumber/core/ast/step_spec.rb
spec/cucumber/core/test/step_spec.rb

Add Cucumber::Core::Ast::Step#original_location.
The intention is to make the location of the OutlineStep easily accessible from the source of a Cucumber::Core::Test::Step.
A Test Step from a Scenario Outline has two locations, the location of the Outline Step and the location of the Example Table Row. This is made explicit by the Gherkin compiler in that a Pickle Step has a locations attribute, that in case of that the Pickle Step was compiled from a Scenario Outline contains both the location of the Outline Step and the Example Table Row. The Cucumber-Ruby compiler does not take this into account, the `Ast::Step`, `Ast::ExpandedOutlineStep` and `Test::Step` all (through include of the `HasLocation` module) all respond to the `#location` method to provide one and only one location. In …

Add #original_location to Cucumber::Core::Ast::Step and Cucumber::Core::Test::Step

---

lib/cucumber/core.rb
lib/cucumber/core/events.rb
lib/cucumber/core/gherkin/parser.rb
spec/cucumber/core/gherkin/parser_spec.rb

Add the `GherkinSourceParsedEvent`
Let the parser issued a `GherkinSourceParsedEvent` with the Gherkin Document after parsing a feature file.
The `GherkinSourceParsedEvent` is useful for the formatters when the LegacyApi is removed from Cucumber-Ruby (https://github.com/cucumber/cucumber-ruby/pull/1230)
The automated test suite has been extended to verify this functionality.

Add the GherkinSourceParsedEvent

---

lib/cucumber/core/test/runner.rb
spec/cucumber/core/test/runner_spec.rb

Let Scenarios with no Steps get the result status Undefined.
After #156 Scenarios with no Steps are compiled into Pickles with no Steps, therefore this change should be made.
Is built on top of #156.
See https://github.com/cucumber/cucumber/issues/249#issue-251216268
The automated test suite has been updated to verify this behavior.

Let Scenarios with no Steps get the result status Undefined

---

Gemfile
cucumber-core.gemspec
lib/cucumber/core/compiler.rb
lib/cucumber/core/events.rb
lib/cucumber/core/gherkin/parser.rb
spec/cucumber/core/gherkin/parser_spec.rb

Update to use gherkin version 6.
Update to use gherkin version 6.
Depends on cucumber/cucumber#444.
Needed to use gherkin version 6.
The automated test suite has been updated to verify this behavior.

Update to use gherkin version 6.

---

.travis.yml

This harmonizes with https://github.com/cucumber/cucumber-ruby/pull/1335 
The latest generally-available JRuby is 9.2.5.0, and this PR updates the version used to that.
https://github.com/cucumber/cucumber-ruby/issues/1336

Travis: use JRuby 9.2.5.0

---

.travis.yml

There's a bug in Google Protobuf gem, which makes it not install in JRuby.
This PR allows CI failures in JRuby to happen, and see JRuby as not-so-supported right now, until that bug is fixed.
- add jruby-9.2.5.0 to allowed-to-fail CI matrix jobs list
- make `travis lint` pass, by lining up all the env vars for the JRuby job
- https://github.com/cucumber/cucumber-ruby/issues/1336 is the Issue which we're waiting for
I want us to have a trustable green build.
CI runs only.
A CI change.

Travis: Allow Failure on jruby until bug fixed

---

.travis.yml

Use latest JRuby.
This PR updates the CI matrix to use latest JRuby, 9.2.6.0.
[JRuby 9.2.6.0 release blog post](https://www.jruby.org/2019/02/11/jruby-9-2-6-0.html)
Be up to date!
CI runs only.
A CI matrix change.

CI: Use latest JRuby 9.2.6.0

---

lib/cucumber/core/event_bus.rb

Make YARD recognize the `registry` parameter, avoiding a warning and improving the API docs.
Warning output:
```
lib/cucumber/core/event_bus.rb:14: [UnknownParam] @param tag has unknown parameter name: a
```
This avoids warning output, and fixes YARD docs.
I have _not_ tested it.
A docs change.

Avoid YARD docstring warning UnknownParam

---

.circleci/config.yml
README.md

The mono-repo already runs on CircleCI. It'll be more convenient to have a single place to look at when it comes to CI issues.
Note: an admin of the repo will have to enable CircleCI to test if it works ;)
The proposed config should run as Travis does (there is not yet an "allow failure" option in CircleCI that said)
Does not apply.

Enable circle ci

---

.circleci/config.yml
.gitignore
spec/capture_warnings.rb

Current build only runs `bundle exec rspec` excluding some of the tests.
Running `bundle exec rake` is a better option.
And also a nightly build as been added like on `cucumber-ruby`

CircleCI: run rake instead of rspec

---

cucumber-core.gemspec

Until we can support `cucumber-messages` 7, we'll force the use of the 6.0 releases.

Force cucumber-message version to 6.x

---

lib/cucumber/core/test/result.rb

This PR fixes the following warning:
```
/home/deivid/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/cucumber-core-3.2.1/lib/cucumber/core/test/result.rb:12: warning: calling private without arguments inside a method may not have the intended effect
```
From reading https://bugs.ruby-lang.org/issues/13249, I don't think `private` is having any effect here, since it's only supposed to affect further methods defined inside the current class method (if at all), and this method does not define any method inside itself.
Avoid warnings.
I think making sure that this doesn't break anything on currently tested rubies is enough. I haven't tried it in ruby 2.7, but since the method call is being removed, it's impossible that the warning won't be fixed :)

Remove unintended `private` call

---

Gemfile
cucumber-core.gemspec
lib/cucumber/core.rb
lib/cucumber/core/compiler.rb
lib/cucumber/core/gherkin/parser.rb
lib/cucumber/core/test/data_table.rb
lib/cucumber/core/test/doc_string.rb
spec/cucumber/core/gherkin/parser_spec.rb
spec/cucumber/core/test/data_table_spec.rb
spec/cucumber/core/test/doc_string_spec.rb

This PR bumps Gherkin to version 9 and uses the `Gherkin::Query` object to locate lines of elements from the feature files.
It will need the [monorepo#845](https://github.com/cucumber/cucumber/pull/845) to be merged/released in order to get it working.
Using existing tests suite.

Use Gherkin::Query and Gherkin 9+

---

lib/cucumber/core/events.rb
lib/cucumber/core/gherkin/parser.rb
spec/cucumber/core/gherkin/parser_spec.rb

A new `envelope` event is emitted in the `eventBus`, which should be emitted with every `cucumber-messages`.

Add envelope event and emit it after parsing gherkin documents

---

lib/cucumber/core.rb
lib/cucumber/core/compiler.rb
lib/cucumber/core/gherkin/parser.rb
spec/cucumber/core/gherkin/parser_spec.rb

Original idea behind CCK was to have predictable ids for comparing messages, but the way we compare messages in CCK (using `json-formatter`) makes this useless finally.

Use IdGenerator::UUID

---

cucumber-core.gemspec
lib/cucumber/core/gherkin/parser.rb

Follow up on new releases in the mono-repo.
This should also allow `cucumber-ruby` to validate against CCK.

Bump Gherkin, messsages and tag-expressions to latest releases

---

CHANGELOG.md
cucumber-core.gemspec

Follow-up of the releases done today on the mono-repo:
- gherkin 14.1.0
- message 12.3.2

Update gherkin and messages (2020/7/30)

---

.rubocop.yml
cucumber-core.gemspec

Hi,
This fixes (very minorly) the `.rubocop.yml` file and adds a dependency on `rubocop-packaging` so that it's easier for downstream (Debian) to maintain this! ❤️ 
Signed-off-by: Utkarsh Gupta <<utkarsh@debian.org>>

Fix .rubocop.yml & add dependency on RuboCop::Packaging

---

cucumber-core.gemspec

RuboCop::Packaging through v0.5 supports
autocorrect for its cops. Thus worth bumping
the version from v0.3 to v0.5.
Signed-off-by: Utkarsh Gupta <<utkarsh@debian.org>>

Bump RuboCop::Packaging to v0.5

---

.rubocop.yml
cucumber-core.gemspec
spec/coverage.rb

This PR enables RuboCop::Packaging and autocorrects
an issue by dropping `require 'bunder/setup` from `spec/`.
Signed-off-by: Utkarsh Gupta <<utkarsh@debian.org>>

Enable RuboCop::Packaging

---

lib/cucumber/core/report/summary.rb
lib/cucumber/core/test/result.rb
spec/cucumber/core/report/summary_spec.rb

**Is your pull request related to a problem? Please describe.**
https://github.com/cucumber/cucumber-ruby/issues/1521
**Describe the solution you have implemented**
Added check on skipped result fo flaky test cases
**Additional context**
https://github.com/cucumber/cucumber-ruby/pull/1531 closed PR with full stack test

1521 Fix skip scenario retry

---

.github/actions/test-ruby/action.yml
.github/workflows/cucumber-ruby-core.yml
.github/workflows/release.yml
cucumber-core.gemspec
docs/RELEASING.md

Add a release workflow based on the one from [cucumber/cucumber-expressions](https://github.com/cucumber/cucumber-expressions)
This also include some workflow refactoring
As there is a single language here, everything is part of a single workflow
Please delete options that are not relevant.
- Refactoring (improvements to code design or tooling that don't change behaviour)
Please add an entry to the relevant section of CHANGELOG.md as part of this pull request.

Add release workflow

---

CHANGELOG.md
lib/cucumber/core/test/case.rb
lib/cucumber/core/test/filters/locations_filter.rb
spec/cucumber/core/test/filters/locations_filter_spec.rb

The Cucumber 4.0 release introduced some regressions in matching scenarios by line numbers other than the exact scenario line. The feature line, tag line, background lines, and step lines all stopped matching their related scenario(s). More context at https://github.com/cucumber/cucumber-ruby/issues/1469
This PR is the first step towards restoring that functionality, and only restores the tags and step lines being matched. It also restores the old tests that used to cover all the matching functionality, pending the ones that still need implementation work.
- Bug fix (non-breaking change which fixes an issue)

Restore support for matching a scenario by its tags' and steps' line numbers.

---

lib/cucumber/core/test/case.rb
lib/cucumber/core/test/data_table.rb
lib/cucumber/core/test/doc_string.rb
lib/cucumber/core/test/empty_multiline_argument.rb
lib/cucumber/core/test/location.rb
lib/cucumber/core/test/step.rb
spec/cucumber/core/test/filters/locations_filter_spec.rb

The Cucumber 4.0 release introduced some regressions in matching scenarios by line numbers other than the exact scenario line. The feature line, tag line, background lines, and step lines all stopped matching their related scenario(s). More context at https://github.com/cucumber/cucumber-ruby/issues/1469
This PR builds on top of https://github.com/cucumber/cucumber-ruby-core/pull/238 to also match multiline arguments like tables and docstrings. Note that I didn't update the CHANGELOG because I think this falls within the changelog line added in the previous PR.
- Bug fix (non-breaking change which fixes an issue)

Restore support for matching a scenario by multiline step argument line numbers

---

.rubocop_todo.yml
CHANGELOG.md
cucumber-core.gemspec
lib/cucumber/core/compiler.rb
lib/cucumber/core/test/case.rb
spec/cucumber/core/test/case_spec.rb
spec/cucumber/core/test/filters/locations_filter_spec.rb
spec/cucumber/core/test/runner_spec.rb

Teach Cucumber::Core::Test::Case to match on parent locations. This will allow it to match on lines like `Feature:`, `Background:`, and `Rule:`. This particular strategy was identified as potentially reasonable while pairing with @mattwynne.
This is the second half of a two-repo PR (including https://github.com/cucumber/gherkin/pull/89) that ultimately resolves the remaining bits of https://github.com/cucumber/cucumber-ruby/issues/1469
- Bug fix (non-breaking change which fixes an issue)
If this looks favorable, and https://github.com/cucumber/gherkin/pull/89 gets merged, I'll update the PR to remove the Gemfile diff pointing at that branch, and resolve the remaining checklist items above.

Teach Cucumber::Core::Test::Case to match on parent locations.

---

cucumber-core.gemspec

Similar to https://github.com/cucumber/cucumber-ruby/pull/1768, this PR adds the funding_uri to the gemspec to help increase visibility using the bundle fund command in Bundler.

Add funding_uri to gemspec

---

.github/workflows/test.yml

This pull request adds Ruby 3.4 to GitHub Actions matrix.
Please delete options that are not relevant.
- Refactoring (improvements to code design or tooling that don't change behaviour)
None.
Your PR is ready for review once the following checklist is
complete. You can also add some checks if you want to.

Add Ruby 3.4 to GitHub Actions matrix
